### ISSUE TITLE
Normal mode start up error

### ISSUE THREAD

**Issue by Gareld-Michael** [ashjack/Sim-U-Kraft-Reloaded#42]
I'm not at all sure what is wrong or what happened but I know that I was going to start a new map and play because my other one may have been corrupted. All I know is that the thing would not start up and I had to force it to shut down. This happened several times. So I did it for A final time to get a game output file and I will post it below for you to see. It appears to simply have gone into an infinite loop that doesn't ever take up enough memory to crash it.
Here it is. Sorry for taking so much of your time, but thank you for paying attention.
[10:41:46] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[10:41:46] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[10:41:46] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[10:41:46] [main/INFO] [FML]: Forge Mod Loader version 7.10.85.1230 for Minecraft 1.7.10 loading
[10:41:46] [main/INFO] [FML]: Java is Java HotSpot(TM) Client VM, version 1.8.0_40, running on Windows 8.1:x86:6.3, installed at C:\Program Files (x86)\Java\jre1.8.0_40
[10:41:46] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[10:41:46] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[10:41:46] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[10:41:46] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[10:41:46] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[10:41:48] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[10:41:48] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[10:41:48] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[10:41:48] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[10:41:48] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[10:41:48] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[10:41:48] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[10:41:49] [main/INFO]: Setting user: Super_Gareld
[10:41:49] [Client thread/INFO]: LWJGL Version: 2.9.1
[10:41:51] [Client thread/INFO] [MinecraftForge]: Attempting early MinecraftForge initialization
[10:41:51] [Client thread/INFO] [FML]: MinecraftForge v10.13.2.1230 Initialized
[10:41:51] [Client thread/INFO] [FML]: Replaced 182 ore recipies
[10:41:51] [Client thread/INFO] [MinecraftForge]: Completed early MinecraftForge initialization
[10:41:51] [Client thread/INFO] [FML]: Searching C:\Users\Gareld-michael\AppData\Roaming\.minecraft\mods for mods
[10:41:53] [Client thread/INFO] [FML]: Forge Mod Loader has identified 4 mods to load
[10:41:53] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, ashjacksimukraftreloaded] at CLIENT
[10:41:53] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, ashjacksimukraftreloaded] at SERVER
[10:41:54] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Sim-U-Kraft Reloaded
[10:41:54] [Client thread/INFO] [FML]: Processing ObjectHolder annotations
[10:41:54] [Client thread/INFO] [FML]: Found 341 ObjectHolder annotations
[10:41:54] [Client thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[10:41:54] [Client thread/INFO] [FML]: Applying holder lookups
[10:41:54] [Client thread/INFO] [FML]: Holder lookups applied
[10:41:54] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[10:41:54] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Starting up SoundSystem...
[10:41:54] [Thread-6/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Initializing LWJGL OpenAL
[10:41:54] [Thread-6/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]:     (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[10:41:54] [Thread-6/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: OpenAL initialized.
[10:41:55] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/blocks/MISSING_ICON_BLOCK_184_null.png
java.io.FileNotFoundException: minecraft:textures/blocks/MISSING_ICON_BLOCK_184_null.png
	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(SourceFile:51) ~[bqq.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SourceFile:55) ~[brg.class:?]
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:125) [bpz.class:?]
	at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:90) [bpz.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(SourceFile:72) [bqf.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110580_a(SourceFile:61) [bqf.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_130088_a(SourceFile:52) [bqf.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:537) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_40]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
[10:41:55] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[10:41:55] [Sound Library Loader/INFO]: Sound engine started
[10:41:55] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/blocks/MISSING_ICON_BLOCK_183_null.png
java.io.FileNotFoundException: minecraft:textures/blocks/MISSING_ICON_BLOCK_183_null.png
	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(SourceFile:51) ~[bqq.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SourceFile:55) ~[brg.class:?]
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:125) [bpz.class:?]
	at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:90) [bpz.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(SourceFile:72) [bqf.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110580_a(SourceFile:61) [bqf.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_130088_a(SourceFile:52) [bqf.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:537) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_40]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
[10:41:55] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/blocks/MISSING_ICON_BLOCK_185_null.png
java.io.FileNotFoundException: minecraft:textures/blocks/MISSING_ICON_BLOCK_185_null.png
	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(SourceFile:51) ~[bqq.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SourceFile:55) ~[brg.class:?]
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:125) [bpz.class:?]
	at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:90) [bpz.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(SourceFile:72) [bqf.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110580_a(SourceFile:61) [bqf.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_130088_a(SourceFile:52) [bqf.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:537) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_40]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
[10:41:55] [Client thread/INFO]: Created: 512x256 textures/blocks-atlas
[10:41:55] [Client thread/INFO]: Created: 256x256 textures/items-atlas
[10:41:55] [Client thread/INFO] [FML]: Forge Mod Loader has successfully loaded 4 mods
[10:41:55] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Sim-U-Kraft Reloaded
[10:41:55] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/blocks/MISSING_ICON_BLOCK_184_null.png
java.io.FileNotFoundException: minecraft:textures/blocks/MISSING_ICON_BLOCK_184_null.png
	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(SourceFile:51) ~[bqq.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SourceFile:55) ~[brg.class:?]
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:125) [bpz.class:?]
	at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:90) [bpz.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(SourceFile:72) [bqf.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110549_a(SourceFile:136) [bqf.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SourceFile:104) [brg.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SourceFile:92) [brg.class:?]
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:598) [bao.class:?]
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:303) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_40]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
[10:41:55] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/blocks/MISSING_ICON_BLOCK_183_null.png
java.io.FileNotFoundException: minecraft:textures/blocks/MISSING_ICON_BLOCK_183_null.png
	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(SourceFile:51) ~[bqq.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SourceFile:55) ~[brg.class:?]
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:125) [bpz.class:?]
	at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:90) [bpz.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(SourceFile:72) [bqf.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110549_a(SourceFile:136) [bqf.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SourceFile:104) [brg.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SourceFile:92) [brg.class:?]
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:598) [bao.class:?]
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:303) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_40]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
[10:41:55] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/blocks/MISSING_ICON_BLOCK_185_null.png
java.io.FileNotFoundException: minecraft:textures/blocks/MISSING_ICON_BLOCK_185_null.png
	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(SourceFile:51) ~[bqq.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SourceFile:55) ~[brg.class:?]
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:125) [bpz.class:?]
	at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:90) [bpz.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(SourceFile:72) [bqf.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110549_a(SourceFile:136) [bqf.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SourceFile:104) [brg.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SourceFile:92) [brg.class:?]
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:598) [bao.class:?]
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:303) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_40]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
[10:41:55] [Client thread/INFO]: Created: 512x256 textures/blocks-atlas
[10:41:55] [Client thread/INFO]: Created: 256x256 textures/items-atlas
[10:41:55] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[10:41:55] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: SoundSystem shutting down...
[10:41:56] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:importantMessage:90]:     Author: Paul Lamb, www.paulscode.com
[10:41:56] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[10:41:56] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[10:41:56] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Starting up SoundSystem...
[10:41:56] [Thread-8/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Initializing LWJGL OpenAL
[10:41:56] [Thread-8/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]:     (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[10:41:56] [Thread-8/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: OpenAL initialized.
[10:41:56] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[10:41:56] [Sound Library Loader/INFO]: Sound engine started
[10:42:03] [Client thread/INFO]: Deleting level Sim-U-Kraft Reloaded 1_7_10
[10:42:03] [Client thread/INFO]: Attempt 1...
[10:42:23] [Server thread/INFO]: Starting integrated minecraft server version 1.7.10
[10:42:23] [Server thread/INFO]: Generating keypair
[10:42:23] [Server thread/INFO]: Converting map!
[10:42:23] [Server thread/INFO]: Scanning folders...
[10:42:23] [Server thread/INFO]: Total conversion count is 0
[10:42:23] [Server thread/INFO] [FML]: Injecting existing block and item data into this server instance
[10:42:23] [Server thread/INFO] [FML]: Applying holder lookups
[10:42:23] [Server thread/INFO] [FML]: Holder lookups applied
[10:42:23] [Server thread/INFO] [FML]: Loading dimension 0 (Sim-U-Kraft Reloaded 1.7.10) (net.minecraft.server.integrated.IntegratedServer@c81ba6)
[10:42:23] [Server thread/INFO] [FML]: Loading dimension 1 (Sim-U-Kraft Reloaded 1.7.10) (net.minecraft.server.integrated.IntegratedServer@c81ba6)
[10:42:23] [Server thread/INFO] [FML]: Loading dimension -1 (Sim-U-Kraft Reloaded 1.7.10) (net.minecraft.server.integrated.IntegratedServer@c81ba6)
[10:42:23] [Server thread/INFO]: Preparing start region for level 0
[10:42:24] [Server thread/INFO]: Preparing spawn area: 8%
[10:42:25] [Server thread/INFO]: Preparing spawn area: 15%
[10:42:27] [Server thread/INFO]: Preparing spawn area: 20%
[10:42:28] [Server thread/INFO]: Preparing spawn area: 26%
[10:42:29] [Server thread/INFO]: Preparing spawn area: 33%
[10:42:30] [Server thread/INFO]: Preparing spawn area: 40%
[10:42:31] [Server thread/INFO]: Preparing spawn area: 47%
[10:42:32] [Server thread/INFO]: Preparing spawn area: 53%
[10:42:33] [Server thread/INFO]: Preparing spawn area: 59%
[10:42:34] [Server thread/INFO]: Preparing spawn area: 65%
[10:42:35] [Server thread/INFO]: Preparing spawn area: 70%
[10:42:36] [Server thread/INFO]: Preparing spawn area: 75%
[10:42:37] [Server thread/INFO]: Preparing spawn area: 81%
[10:42:38] [Server thread/INFO]: Preparing spawn area: 88%
[10:42:39] [Server thread/INFO]: Preparing spawn area: 97%
Apr 11, 2015 10:42:39 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
Apr 11, 2015 10:42:39 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
Apr 11, 2015 10:42:39 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
Apr 11, 2015 10:42:39 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
Apr 11, 2015 10:42:39 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
Apr 11, 2015 10:42:39 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
[10:42:39] [Server thread/INFO]: Changing view distance to 6, from 10
Apr 11, 2015 10:42:39 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
Apr 11, 2015 10:42:39 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
Apr 11, 2015 10:42:39 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
Apr 11, 2015 10:42:39 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
Apr 11, 2015 10:42:39 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
Apr 11, 2015 10:42:39 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
Apr 11, 2015 10:42:39 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
Apr 11, 2015 10:42:39 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
Apr 11, 2015 10:42:39 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
Apr 11, 2015 10:42:39 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
Apr 11, 2015 10:42:39 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
Apr 11, 2015 10:42:39 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
Apr 11, 2015 10:42:39 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
Apr 11, 2015 10:42:39 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
Apr 11, 2015 10:42:39 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
Apr 11, 2015 10:42:39 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
Apr 11, 2015 10:42:39 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
Apr 11, 2015 10:42:39 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
Apr 11, 2015 10:42:39 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
Apr 11, 2015 10:42:39 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
Apr 11, 2015 10:42:39 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
Apr 11, 2015 10:42:39 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
Apr 11, 2015 10:42:39 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
Apr 11, 2015 10:42:39 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
Apr 11, 2015 10:42:40 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
Apr 11, 2015 10:42:40 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
Apr 11, 2015 10:42:40 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
Apr 11, 2015 10:42:40 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
Apr 11, 2015 10:42:40 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
Apr 11, 2015 10:42:40 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
Apr 11, 2015 10:42:40 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
Apr 11, 2015 10:42:40 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
Apr 11, 2015 10:42:40 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
Apr 11, 2015 10:42:40 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
Apr 11, 2015 10:42:40 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
[10:42:40] [Netty Client IO #0/INFO] [FML]: Server protocol version 1
[10:42:40] [Netty IO #1/INFO] [FML]: Client protocol version 1
Apr 11, 2015 10:42:40 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
Apr 11, 2015 10:42:40 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
Apr 11, 2015 10:42:40 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
Apr 11, 2015 10:42:40 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
Apr 11, 2015 10:42:40 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
Apr 11, 2015 10:42:40 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
[10:42:40] [Netty IO #1/INFO] [FML]: Client attempting to join with 4 mods : FML@7.10.85.1230,Forge@10.13.2.1230,mcp@9.05,ashjacksimukraftreloaded@1.0.2b
[10:42:40] [Netty IO #1/INFO] [FML]: Attempting connection with missing mods [] at CLIENT
[10:42:40] [Netty Client IO #0/INFO] [FML]: Attempting connection with missing mods [] at SERVER
Apr 11, 2015 10:42:40 AM ashjack.simukraftreloaded.client.ClientTickHandler onTickInGame
INFO: CommTH: in Gui Main menu
[10:42:40] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[10:42:40] [Server thread/INFO]: Super_Gareld[local:E:6e84e86f] logged in with entity id 236 at (4.5, 67.0, 68.5)
[10:42:40] [Server thread/INFO]: Super_Gareld joined the game
[10:42:40] [Client thread/INFO] [FML]: [Client thread] Client side modded connection established
[10:42:43] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 3919ms behind, skipping 78 tick(s)
[10:42:46] [Server thread/INFO]: Saving and pausing game...
[10:42:46] [Server thread/INFO]: Saving chunks for level 'Sim-U-Kraft Reloaded 1.7.10'/Overworld
[10:42:49] [Server thread/INFO]: Saving chunks for level 'Sim-U-Kraft Reloaded 1.7.10'/Nether
[10:42:49] [Server thread/INFO]: Saving chunks for level 'Sim-U-Kraft Reloaded 1.7.10'/The End
[10:42:49] [Server thread/INFO] [STDOUT]: [ashjack.simukraftreloaded.common.CommonTickHandler:onTickInGame:114]: Haven't run startup - doing that now
Apr 11, 2015 10:42:49 AM ashjack.simukraftreloaded.common.CommonTickHandler onTickInGame
INFO: CommTH: Startup - set serverWorld/currentWorld
[10:42:49] [Server thread/INFO] [STDOUT]: [ashjack.simukraftreloaded.common.CommonTickHandler:onTickInGame:120]: Running Reset World Function
Apr 11, 2015 10:42:49 AM ashjack.simukraftreloaded.core.registry.SimukraftReloaded resetAndLoadNewWorld
INFO: RESETTING and loading world on SERVER SIDE
Apr 11, 2015 10:42:49 AM ashjack.simukraftreloaded.common.GameStates saveStates
INFO: GameStates: saveStates() called BOTH sides, credits saved as 10.0
[10:42:49] [Server thread/INFO] [STDOUT]: [ashjack.simukraftreloaded.client.Gui.other.GuiRunMod:func_73866_w_:30]: Initializing GUI
[10:42:50] [Server thread/INFO]: Saving and pausing game...
[10:42:50] [Server thread/INFO]: Saving chunks for level 'Sim-U-Kraft Reloaded 1.7.10'/Overworld
[10:42:50] [Client thread/INFO] [STDOUT]: [ashjack.simukraftreloaded.client.Gui.other.GuiRunMod:func_146284_a:82]: Playing Sim-U-Kraft Reloaded in normal mode
[10:42:51] [Server thread/INFO]: Saving chunks for level 'Sim-U-Kraft Reloaded 1.7.10'/Nether
[10:42:51] [Server thread/INFO]: Saving chunks for level 'Sim-U-Kraft Reloaded 1.7.10'/The End

**Comment by Gareld-Michael** [comment]
Sorry for being late but I just read about someone having the same exact problem as me so if you need a game output log you now have one

**Comment by ashjack** [comment]
Thanks for the log, but it doesn't give any useful information. This bug is, as you already saw known, and the log doesn't give any information (not your fault) on the matter. Thanks for creating the issue anyway.
