### ISSUE TITLE
Marriage Crash

### ISSUE THREAD

**Issue by aceliip** [ashjack/Sim-U-Kraft-Reloaded#61]
game crashed when a builder sat idle waiting for a building to be chosen, I stepped away to eat dinner and left the game running to collect rent but left the builder waiting for orders and came back and the game had already crashed when i got back.
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 10/10/15 6:31 PM
Description: Exception in server tick loop

java.lang.StringIndexOutOfBoundsException: String index out of range: -1
    at java.lang.String.substring(Unknown Source)
    at ashjack.simukraftreloaded.common.Relationship.changeFemaleSurname(Relationship.java:542)
    at ashjack.simukraftreloaded.common.Relationship.levelIncrease(Relationship.java:442)
    at ashjack.simukraftreloaded.common.Relationship.meddleWithRelationship(Relationship.java:752)
    at ashjack.simukraftreloaded.folk.FolkData.onUpdate(FolkData.java:1085)
    at ashjack.simukraftreloaded.folk.FolkData.triggerAllUpdates(FolkData.java:563)
    at ashjack.simukraftreloaded.common.CommonTickHandler.onTickInGame(CommonTickHandler.java:71)
    at ashjack.simukraftreloaded.common.CommonTickHandler.tick(CommonTickHandler.java:43)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_8_CommonTickHandler_tick_ServerTickEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_60, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 700125656 bytes (667 MB) / 1495920640 bytes (1426 MB) up to 7408844800 bytes (7065 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx7G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn1G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 6 mods loaded, 6 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAA  mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAA  FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1492-1.7.10.jar) 
    UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAA  Forge{10.13.4.1492} [Minecraft Forge](forge-1.7.10-10.13.4.1492-1.7.10.jar) 
    UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAA  ResourceLoader{1.2} [Resource Loader](ResourceLoader-1.2.jar) 
    UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAA  ashjacksimukraftreloaded{1.0.4} [Sim-U-Kraft Reloaded](Sim-U-Kraft Reloaded-1.0.4.jar) 
    UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAA  sus{4.1.1} [Superheroes Unlimited Mod](Superheroes Unlimited Mod-1.7.10-4.1.1.jar) 
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['Maxy501'/126544, l='New World', x=157.68, y=71.00, z=243.57]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by ashjack** [comment]
This issue is caused because of a piece of code I overlooked while programming the race system. Some races do not have surnames, but when marrying folks, the game looks for a surname anyway. When it doesn't find one, it crashes. Although this is actually fixed in 1.0.4a, the build itself is broken, so the bug still exists. You can expect it to be fixed in 1.0.4b though.

**Comment by xXXIMMATTHEWXXx** [comment]
Hello! I am porting this port to try and update the inactivity from the person who updated this mod. Please [recreate the issue here.](https://github.com/xXXIMMATTHEWXXx/Sim-u-kraft-Restored)

**Comment by aceliip** [comment]
I have no idea what this is or who you are but do not email me again

**Comment by xXXIMMATTHEWXXx** [comment]
Hello! This is Matthew from github. You made an issue on github and I
replied to it. Github has emailed you not me silly!

**Comment by ashjack** [comment]
Fixed in 1.0.4b
