### ISSUE TITLE
when tyr to start normal mode sim u craft crash report

### ISSUE THREAD

**Issue by nicksupercar** [ashjack/Sim-U-Kraft-Reloaded#67]
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at ashjack.simukraftreloaded.folk.FolkData.generateRace(FolkData.java:2537)
	at ashjack.simukraftreloaded.folk.FolkData.<init>(FolkData.java:238)
	at ashjack.simukraftreloaded.folk.FolkData.generateNewFolk(FolkData.java:2120)
	at ashjack.simukraftreloaded.client.Gui.other.GuiRunMod.func_146284_a(GuiRunMod.java:86)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
I don't know what any of this means so if its something I'm doing wrong let me know also it wont work in any of the other modes either it wont create a starting sim person

**Comment by ashjack** [comment]
You have not installed the mod correctly. Please ensure that you have followed the installation instructions that were included in the zip file.
