### ISSUE TITLE
Crash occurs when normal mode is selected

### ISSUE THREAD

**Issue by simonlii** [ashjack/Sim-U-Kraft-Reloaded#70]
---- Minecraft Crash Report ----
// Sorry :(

Time: 2016/2/7 下午 5:53
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at ashjack.simukraftreloaded.folk.FolkData.generateRace(FolkData.java:2537)
	at ashjack.simukraftreloaded.folk.FolkData.<init>(FolkData.java:238)
	at ashjack.simukraftreloaded.folk.FolkData.generateNewFolk(FolkData.java:2120)
	at ashjack.simukraftreloaded.client.Gui.other.GuiRunMod.func_146284_a(GuiRunMod.java:86)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at ashjack.simukraftreloaded.folk.FolkData.generateRace(FolkData.java:2537)
	at ashjack.simukraftreloaded.folk.FolkData.<init>(FolkData.java:238)
	at ashjack.simukraftreloaded.folk.FolkData.generateNewFolk(FolkData.java:2120)
	at ashjack.simukraftreloaded.client.Gui.other.GuiRunMod.func_146284_a(GuiRunMod.java:86)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

-- Affected screen --
Details:
	Screen name: ashjack.simukraftreloaded.client.Gui.other.GuiRunMod

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['simonlii'/1, l='MpServer', x=61.95, y=5.62, z=-57.99]]
	Chunk stats: MultiplayerChunkCache: 440, 449
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (63,4,-50), Chunk: (at 15,0,14 in 3,-4; contains blocks 48,0,-64 to 63,255,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 104 game time, 104 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 7 total; [EntitySlime['史?姆'/16, l='MpServer', x=46.31, y=4.00, z=-110.07], EntitySlime['史?姆'/17, l='MpServer', x=45.42, y=4.00, z=-103.51], EntityClientPlayerMP['simonlii'/1, l='MpServer', x=61.95, y=5.62, z=-57.99], EntitySlime['史?姆'/18, l='MpServer', x=138.07, y=4.00, z=-12.68], EntitySlime['史?姆'/6, l='MpServer', x=69.03, y=4.00, z=-91.06], EntitySlime['史?姆'/13, l='MpServer', x=38.75, y=4.00, z=16.91], EntitySlime['史?姆'/14, l='MpServer', x=33.06, y=4.00, z=11.44]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_71, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 147603272 bytes (140 MB) / 359858176 bytes (343 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_C1 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) 
	UCHIJAAAA	journeymap{5.1.3} [JourneyMap] (journeymap-1.7.10-5.1.3-unlimited.jar) 
	UCHIJAAAA	ashjacksimukraftreloaded{1.0.4a} [Sim-U-Kraft Reloaded] (Sim-U-Kraft Reloaded - 1.0.4a.jar) 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '3.3.11672 Compatibility Profile Context' Renderer: 'ATI Radeon HD 4600 Series'
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: ATI Radeon HD 4600 Series GL version 3.3.11672 Compatibility Profile Context, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: ?体中文 (中?)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by ashjack** [comment]
You have not installed the mod correctly. Please ensure that you have followed the installation instructions that were included in the zip file.
